name: build

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      platform:
        required: true
        type: string
      build-args:
        required: false
        type: string
      release-id:
        required: false
        type: string
      upload-artifacts:
        required: false
        type: boolean

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        if: startsWith(inputs.platform, 'macos')

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install additional system dependencies (Linux)
        if: startsWith(inputs.platform, 'ubuntu')
        run: |-
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install frontend dependencies
        run: npm install

      - id: tauri-build
        name: Build with tauri-action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_STRIP: ${{ startsWith(inputs.platform, 'ubuntu') }}
        with:
          args: ${{ inputs.build-args }}
          releaseId: ${{ inputs.release-id }}

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v4
        if: startsWith(inputs.platform, 'ubuntu')
        with:
          name: binaries-linux
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.deb
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.rpm
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.AppImage

      - name: Upload MacOS binaries
        uses: actions/upload-artifact@v4
        if: startsWith(inputs.platform, 'macos')
        with:
          name: binaries-macos
          path: |
            ${{ github.workspace }}/src-tauri/target/universal-apple-darwin/release/bundle/**/*.dmg

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        if: startsWith(inputs.platform, 'windows')
        with:
          name: binaries-windows
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.exe
