name: 'CI'

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  pr-ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, 'ubuntu-22.04']

    runs-on: ${{ matrix.platform }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install additional system dependencies
        if: ${{ matrix.platform == 'ubuntu-22.04' }}
        run: |-
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            librust-pango-dev \
            libatk1.0-dev \
            librust-atk-dev \
            librust-atk-sys-dev \
            libgtk-3-dev \
            librust-gtk-sys-dev \
            libjavascriptcoregtk-4.1-dev

      - name: Install frontend dependencies
        run: npm install

      - name: Build with tauri-action
        uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.platform == 'windows-latest' && '--bundles nsis' || '' }}
