name: 'CI'

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: ''
            target: aarch64-apple-darwin
          - platform: 'macos-latest'
            args: ''
            target: x86_64-apple-darwin
          - platform: 'ubuntu-22.04'
            args: '--bundles deb,rpm'
            target: ''
          - platform: 'ubuntu-22.04-arm'
            args: '--bundles deb,rpm'
            target: ''
          - platform: 'ubuntu-24.04'
            args: '--bundles appimage'
            target: ''
          - platform: 'ubuntu-24.04-arm'
            args: '--bundles appimage'
            target: ''
          - platform: 'windows-latest'
            args: '--bundles nsis'
            target: ''
    uses: ./.github/workflows/build.yml
    with:
      version: 0.0.0-${{ github.sha }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      upload-artifacts: true
    secrets: inherit
    permissions:
      contents: write
