name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            builds-args: '--bundles nsis'
            target: ''
          - platform: 'macos-latest'
            target: aarch64-apple-darwin
          - platform: 'macos-latest'
            target: x86_64-apple-darwin
          - platform: 'ubuntu-22.04'
            target: ''
          - platform: 'ubuntu-22.04-arm'
            target: ''
          - platform: 'ubuntu-24.04'
            target: ''
          - platform: 'ubuntu-24.04-arm'
            target: ''

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
    secrets: inherit
    permissions:
      contents: write
