name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: ''
          - platform: 'ubuntu-latest'
            target: ''
          - platform: 'windows-latest'
            target: ''

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
    secrets: inherit
    permissions:
      contents: write