name: 'Release: Build & Package App'

on:
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, 'ubuntu-22.04']
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      build-args: ${{ matrix.platform == 'windows-latest' && '--bundles nsis' || '' }}
      release-id: ${{ github.event.release.id }}
    secrets: inherit
