name: 'Release: Build & Package App'

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: ''
            target: aarch64-apple-darwin
          - platform: 'macos-latest'
            args: ''
            target: x86_64-apple-darwin
          - platform: 'ubuntu-22.04'
            args: ''
            target: ''
          - platform: 'windows-latest'
            args: '--bundles nsis'
            target: ''
    uses: ./.github/workflows/build.yml
    with:
      release-id: ${{ github.event.release.id }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
    secrets: inherit
    permissions:
      contents: write
